name: Databricks CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for semantic-release to push tags

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CLI and dependencies
        run: |
          pip install --upgrade databricks-cli
          npm install --global semantic-release \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/exec \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator

      - name: Validate Databricks Bundle
        run: |
          databricks bundle validate

      - name: Deploy Databricks Bundle
        run: |
          databricks bundle deploy

      # - name: Run Tests
      #   run: |
      #     # Replace with your own test logic or command
      #     pytest tests/

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release
