name: 'Dev Deployment'

concurrency: '1'

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  validate:
    name: 'Validate Databricks Bundle'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - name: Validate bundle
        run: databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  deploy:
    name: 'Deploy Databricks Bundle'
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main

      - name: Deploy bundle
        run: databricks bundle deploy
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  # run-tests:
  #   name: 'Run Bundle Job'
  #   runs-on: ubuntu-latest
  #   needs: deploy

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: databricks/setup-cli@main

  #     - name: Run Databricks Job
  #       run: databricks bundle run my-job --refresh-all
  #       env:
  #         DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  #         DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  #         DATABRICKS_BUNDLE_ENV: dev

  #     - name: Run local Python tests
  #       run: pytest tests/
